// https://metahub.info/jwa-dinodex/

// https://docs.google.com/spreadsheets/d/14ZoguIzdducEeJBqR-S7tp1KeaAjQpW_-lrvgwO2XZw/edit#gid=0
// https://docs.google.com/spreadsheets/d/1POeswkG1wrf4BT2rzaWLuX7F0VzeeZe7mrSdNVS6HkY/edit#gid=1345722362
// https://docs.google.com/spreadsheets/d/1ZLm2X8rjlFm94qJW8JtlDpmirkS4SICeoh681Oe35Zg/template/preview
// https://docs.google.com/spreadsheets/d/1MXypWwwvB6HJlxxdq8jZlfOCmv54sEs-F3icrkUS0lc/edit#gid=0
// https://docs.google.com/spreadsheets/d/1Qve2ewd_-QXr21mjaQ76toyrhtOZpNOcyde0UyA_xJQ/edit#gid=327547420

// http://jurassic-world-alive.wikia.com/wiki/List_of_Abilities
// Quick-Use Abilities
// These moves are usable every turn with no cooldown times or delayed usage. Usually, they are lesser moves and rely entirely on the creature's damage stat.
// Charged-Use Abilities
// These moves are not necessarily usable every turn as there are usually cooldown times or delayed usage per action, in which case the creature using the move may have to wait a given number of turns to charge up the ability again. Usually, these are harder-hitting moves or have additional effects that will negatively affect the opponent or positively affect the creature using the move.
// Passive Abilities
// These abilities are not manually usable at all and instead act automatically in battle whenever required. While it may seem like some of these passive abilities unfairly take the place of an actual usable ability, these abilities may actually be more helpful than usable moves in many scenarios.
// Swap-in Abilities
// Some creatures now have access to Swap-In Abilities (or SIA for short). When you perform a SIA, you get the benefit of having swapped out your previous creature, having swapped in your new creature and performing an ability, all in a single action!

// https://metahub.info/jurassic-world-alive/550/jwa-recipes-for-all-hybrids-what-dna-do-you-need/

var Moves = [
	{ name: "Adrenaline Surge",			damage: 0, cooldown: 3, effect: "Act first. Cleanse. Increase damage 25% for 4 turns. Regenerate 25%." },
	{ name: "Armor Piercing Impact",	damage: 1.5, cooldown: 2, effect: "Bypasses Thick Skin" },
	{ name: "Armor Piercing Rampage",	damage: 2, cooldown: 1, effect: "Bypasses Thick Skin" },
	{ name: "Armor Piercing Strike",	damage: 1, cooldown: 0, effect: "Bypasses Thick Skin" },
	{ name: "Bleeding Bite",			damage: 0.5, cooldown: 2, effect: "Inflict 0.66x damage per turn for 3 turns" },
	{ name: "Cleansing Impact",			damage: 1.5, cooldown: 2, effect: "Cleanse self." },
	{ name: "Critical Impact",			damage: 1.5, cooldown: 2, effect: "Critical Chance +40%" },
	{ name: "Decelerating Impact",		damage: 1.5, cooldown: 3, effect: "Target's speed is reduced 90% 2 turns" },
	{ name: "Defensive Graze",			damage: 0.66, cooldown: 2, effect: "Shield 50% for 2 turns" },
	{ name: "Distracting Strike",		damage: 1, cooldown: 2, effect: "Target damage reduced 50% 2 turns" },
	{ name: "Exploit Wound",			damage: 0, cooldown: 2, effect: "Target is Vulnerable this turn and for the next 2 turns. DoT 1x for 2 turns" },
	{ name: "Expose Weak Spot",			damage: 1, cooldown: 3, effect: "Then target is Vulnerable for this turn and next 3 turns." },
	{ name: "Extended Critical Strike",	damage: 1, cooldown: 3, effect: "Critical Chance +60% for 3 turns" },
	{ name: "Ferocious Strike",			damage: 1, cooldown: 3, effect: "Damage increased +50% for 3 turns" },
	{ name: "Ferocity",					damage: 0, cooldown: 3, effect: "Damage increased +50% for 3 turns" },
	{ name: "Greater Stunning Strike",	damage: 1, cooldown: 3, effect: "75% chance to stun this turn" },
	{ name: "Impact",					damage: 1.5, cooldown: 2, effect: "None" },
	{ name: "Instant Charge",			damage: 1, cooldown: 2, effect: "Act first. Guaranteed stun this turn" },
	{ name: "Instant Cripple",			damage: 0, cooldown: 1, effect: "Act First. Target's damage reduced 90% this turn." },
	{ name: "Instant Invincibility",	damage: 0, cooldown: 3, effect: "Act first. Shield 100% for 1 turn." },
	{ name: "Instant Pinning Strike",	damage: 1, cooldown: 1, effect: "Act first. Cannot Swap this turn." },
	{ name: "Lockdown Strike",			damage: 1, cooldown: 3, effect: "Cannot Swap 3 turns" },
	{ name: "Minimal Stunning Strike",	damage: 1, cooldown: 0, effect: "10% Chance to stun this turn." },
	{ name: "Minimal Wounding Strike",	damage: 1, cooldown: 0, effect: "DoT 0.1x over 2 turns" },
	{ name: "Minor Wounding Strike",	damage: 1, cooldown: 0, effect: "Dot 0.15x over 2 turns" },
	{ name: "Nullifying Strike",		damage: 1, cooldown: 0, effect: "Remove Positive Effects" },
	{ name: "Pinning Strike",			damage: 1, cooldown: 0, effect: "Cannot Swap 1 turn" },
	{ name: "Pounce",					damage: 2, cooldown: 1, effect: "None" },
	{ name: "Short Defense",			damage: 1, cooldown: 2, effect: "50% shield for 2 turns" },
	{ name: "Slowing Impact",			damage: 1.5, cooldown: 4, effect: "Decrease speed 50% for 3 turns" },
	{ name: "Strike",					damage: 1, cooldown: 0, effect: "None" },
	{ name: "Strike and Run",			damage: 1, cooldown: 1, effect: "Automatic Swap." },
	{ name: "Stunning Impact",			damage: 1.5, cooldown: 2, effect: "33% chance to stun 2 turns" },
	{ name: "Thagomizer",				damage: 1.5, cooldown: 3, effect: "Target's speed -50% for 3 turns" },
	{ name: "Velocity Strike",			damage: 1, cooldown: 2, effect: "Increase speed 75% for 2 turns." },
	{ name: "Wounding Strike",			damage: 1, cooldown: 4, effect: "Dot 0.5x per turn for 2 turns" },
	// mine
	{ name: "Impact and Run",			damage: 1.5, cooldown: 1, effect: "Automatic Swap", delay: 1 },
	// { name: "Swap in Strike",		damage: 1, cooldown: 1, effect: "" },
];

var Dinos = [
	// arena
	{ name: "Allosaurus", 				rarity: "Common", 	health: 4200, 	damage: 1170, 	speed: 104, 	defense: "0%", 	quick: "Defense Shattering Strike", special: "Armor Piercing Impact", special2: "", special3: "" },
	{ name: "Amargasaurus", 			rarity: "Rare", 	health: 4800, 	damage: 1053, 	speed: 103, 	defense: "0%", 	quick: "Pinning Strike", special: "Decelerating Impact", special2: "Slowing Impact", special3: "" },
	{ name: "Ankylosaurus", 			rarity: "Epic", 	health: 4650, 	damage: 999, 	speed: 112, 	defense: "25%", quick: "Strike", special: "Short Defense", special2: "Instant Invincibility", special3: "" },
	{ name: "Ankylosaurus Gen 2", 		rarity: "Common", 	health: 4200, 	damage: 981, 	speed: 112, 	defense: "25%", quick: "Vulnerability Strike", special: "Long Protection", special2: "", special3: "" },
	{ name: "Apatosaurus", 				rarity: "Common", 	health: 6000, 	damage: 855, 	speed: 101, 	defense: "0%", 	quick: "Strike", special: "Decelerating Impact", special2: "", special3: "" },
	{ name: "Dilophosaurus", 			rarity: "Rare", 	health: 2760, 	damage: 999, 	speed: 123, 	defense: "0%", 	quick: "Nullifying Strike", special: "Distracting Strike", special2: "Slowing Impact", special3: "" },
	{ name: "Dilophosaurus Gen 2", 		rarity: "Common", 	health: 2880, 	damage: 990, 	speed: 121, 	defense: "0%", 	quick: "Nullifying Strike", special: "Distracting Impact", special2: "", special3: "" },
	{ name: "Dimetrodon", 				rarity: "Rare", 	health: 3000, 	damage: 990, 	speed: 116, 	defense: "0%", 	quick: "Armor Piercing Strike", special: "Armor Piercing Impact", special2: "Critical Impact", special3: "" },
	{ name: "Einiosaurus", 				rarity: "Common", 	health: 4020, 	damage: 1008, 	speed: 114, 	defense: "5%", 	quick: "Strike", special: "Stunning Impact", special2: "", special3: "" },
	{ name: "Euoplocephalus", 			rarity: "Common", 	health: 4500, 	damage: 900, 	speed: 110, 	defense: "40%", quick: "Strike", special: "Impact", special2: "", special3: "" },
	{ name: "Gorgosaurus", 				rarity: "Rare", 	health: 3330, 	damage: 1215, 	speed: 102, 	defense: "0%", 	quick: "Armor Piercing Strike", special: "Armor Piercing Impact", special2: "Ferocious Strike", special3: "" },
	{ name: "Iguanodon", 				rarity: "Common", 	health: 4350, 	damage: 972, 	speed: 108, 	defense: "0%", 	quick: "Superiority Strike", special: "Greater Stunning Impact", special2: "", special3: "" },
	{ name: "Kaprosuchus", 				rarity: "Rare", 	health: 2850, 	damage: 945, 	speed: 125, 	defense: "0%", 	quick: "Minor Wounding Strike", special: "Ferocious Strike", special2: "Adrenaline Surge", special3: "" },
	{ name: "Kentrosaurus", 			rarity: "Epic", 	health: 3510, 	damage: 1053, 	speed: 110, 	defense: "0%", 	quick: "Strike", special: "Thagomizer", special2: "Instant Cripple", special3: "" },
	{ name: "Majungasaurus", 			rarity: "Common", 	health: 2400, 	damage: 864, 	speed: 107, 	defense: "0%", 	quick: "Strike", special: "Instant Pinning Strike", special2: "", special3: "" },
	{ name: "Megalosaurus", 			rarity: "Rare", 	health: 2130, 	damage: 864, 	speed: 102, 	defense: "0%", 	quick: "Pinning Strike", special: "Lockdown Strike", special2: "Bleeding Bite", special3: "" },
	{ name: "Monolophosaurus Gen 2", 	rarity: "Common", 	health: 2850, 	damage: 990, 	speed: 126, 	defense: "0%", 	quick: "Nullifying Strike", special: "Distracting Impact", special2: "", special3: "" },
	{ name: "Nodosaurus", 				rarity: "Rare", 	health: 4800, 	damage: 936, 	speed: 112, 	defense: "20%", quick: "Strike", special: "Armor Piercing Impact", special2: "Short Defense", special3: "" },
	{ name: "Nundasuchus", 				rarity: "Common", 	health: 2970, 	damage: 990, 	speed: 127, 	defense: "0%", 	quick: "Strike", special: "Ferocious Strike", special2: "", special3: "" },
	{ name: "Parasaurolophus", 			rarity: "Common", 	health: 3720, 	damage: 990, 	speed: 113, 	defense: "0%", 	quick: "Superiority Strike", special: "Impact and Run", special2: "", special3: "" },
	{ name: "Postosuchus", 				rarity: "Rare", 	health: 3000, 	damage: 1008, 	speed: 126, 	defense: "0%", 	quick: "Defense Shattering Strike", special: "Ferocious Impact", special2: "Adrenaline Pulse", special3: "" },
	{ name: "Pyroraptor", 				rarity: "Epic", 	health: 2310, 	damage: 1116, 	speed: 128, 	defense: "0%", 	quick: "Strike", special: "Pounce", special2: "Armor Piercing Impact", special3: "" },
	{ name: "Rajasaurus", 				rarity: "Epic", 	health: 2310, 	damage: 864, 	speed: 103, 	defense: "0%", 	quick: "Pinning Strike", special: "Lockdown Strike", special2: "Exploit Wound", special3: "" },
	{ name: "Sinoceratops", 			rarity: "Epic", 	health: 4050, 	damage: 999, 	speed: 113, 	defense: "15%", quick: "Strike", special: "Stunning Impact", special2: "Instant Charge", special3: "" },
	{ name: "Spinosaurus", 				rarity: "Rare", 	health: 2700, 	damage: 1026, 	speed: 123, 	defense: "0%", 	quick: "Minimal Wounding Strike", special: "Wounding Strike", special2: "Expose Weak Spot", special3: "" },
	{ name: "Stegosaurus", 				rarity: "Common", 	health: 3720, 	damage: 1116, 	speed: 116, 	defense: "15%",	quick: "Superiority Strike", special: "Thagomizer", special2: "", special3: "" },
	{ name: "Suchomimus", 				rarity: "Common", 	health: 2760, 	damage: 1026, 	speed: 115, 	defense: "0%", 	quick: "Strike", special: "Gashing Wound", special2: "", special3: "" },
	{ name: "Tanycolagreus", 			rarity: "Common", 	health: 2550, 	damage: 1143, 	speed: 128, 	defense: "0%", 	quick: "Armor Piercing Strike", special: "Nullifying Strike", special2: "", special3: "" },
	{ name: "Tenontosaurus", 			rarity: "Rare", 	health: 3900, 	damage: 909, 	speed: 126, 	defense: "0%", 	quick: "Strike", special: "Greater Stunning Strike", special2: "Distracting Strike", special3: "" },
	{ name: "Triceratops", 				rarity: "Rare", 	health: 4200, 	damage: 981, 	speed: 115, 	defense: "20%", quick: "Minor Stunning Strike", special: "Stunning Impact", special2: "Greater Stunning Strike", special3: "" },
	{ name: "Triceratops Gen 2", 		rarity: "Common", 	health: 3960, 	damage: 1035, 	speed: 112, 	defense: "10%", quick: "Low Stunning Strike", special: "Rampage", special2: "", special3: "" },
	{ name: "Tyrannosaurus Gen 2", 		rarity: "Rare", 	health: 3900, 	damage: 1206, 	speed: 103, 	defense: "0%", 	quick: "Armor Piercing Strike", special: "Armor Piercing Impact", special2: "Armor Piercing Rampage", special3: "" },
	{ name: "Tyrannosaurus Rex", 		rarity: "Epic", 	health: 4050, 	damage: 1260, 	speed: 102, 	defense: "0%", 	quick: "Armor Piercing Strike", special: "Armor Piercing Impact", special2: "Armor Piercing Rampage", special3: "" },
	{ name: "Utahraptor", 				rarity: "Rare", 	health: 2400, 	damage: 1044, 	speed: 128, 	defense: "0%", 	quick: "Strike", special: "Pounce", special2: "Critical Impact", special3: "" },
	{ name: "Velociraptor", 			rarity: "Common", 	health: 1800, 	damage: 1035, 	speed: 132, 	defense: "0%", 	quick: "Strike", special: "Pounce", special2: "", special3: "" },
	// non-arena
	{ name: "Edmontosaurus", 			rarity: "Rare", 	health: 4350, 	damage: 900, 	speed: 123, 	defense: "0%", 	quick: "Superiority Strike", special: "Greater Stunning Strike", special2: "Strike and Run", special3: "" },
	{ name: "Lythronax", 				rarity: "Common", 	health: 2340, 	damage: 900, 	speed: 102, 	defense: "0%", 	quick: "Strike", special: "Lockdown Strike", special2: "", special3: "" },
	{ name: "Ophiacodon", 				rarity: "Common", 	health: 3000, 	damage: 916, 	speed: 108, 	defense: "0%", 	quick: "Strike", special: "Extended Critical Strike", special2: "", special3: "" },
	{ name: "Proceratosaurus", 			rarity: "Rare", 	health: 2850, 	damage: 900, 	speed: 124, 	defense: "0%", 	quick: "Nullifying Strike", special: "Distracting Impact", special2: "Slowing Impact", special3: "" },
	{ name: "Tarbosaurus", 				rarity: "Common", 	health: 3950, 	damage: 1170, 	speed: 104, 	defense: "0%", 	quick: "Defense Shattering Strike", special: "Armor Piercing Impact", special2: "", special3: "" },
	{ name: "Tuojiangosaurus", 			rarity: "Rare", 	health: null, 	damage: null,	speed: null,	defense: "", 	quick: "Strike", special: "Thagomizer", special2: "Distracting Strike", special3: "" },
	{ name: "Wuerhosaurus", 			rarity: "Rare", 	health: 3960, 	damage: 1115, 	speed: 115, 	defense: "10%", quick: "Strike", special: "Thagomizer", special2: "Instant Cripple", special3: "" },
	// hybrid
	{ name: "Einiasuchus", 				rarity: "Rare", 	health: 3900, 	damage: 908, 	speed: 115, 	defense: "10%", quick: "Minimal Stunning Strike", special: "Stunning Impact", special2: "Cleansing Impact", special3: "Ferocious Strike" },
	// mine
	{ name: "Dracorex Gen 2",			rarity: "Common", 	health: null, 	damage: null, 	speed: 119, 	defense: "0%", 	quick: "Low Stunning Strike", special: "Impact and Run", special2: "", special3: "" },
	{ name: "Purussaurus Gen 2",		rarity: "Common", 	health: null, 	damage: null, 	speed: 111, 	defense: "10%", quick: "Vulnerability Strike", special: "Lockdown Impact", special2: "", special3: "" },
	{ name: "Hatzegopteryx",			rarity: "Common", 	health: null, 	damage: null, 	speed: 114, 	defense: "0%", quick: "Superiority Strike", special: "Impact and Run", special2: "", special3: "" },
	{ name: "Deinocheirus", 			rarity: "Common",	health: null, 	damage: null, 	speed: 130, 	defense: "0%", 	quick: "Minimal Speedup Strike", special: "Rampage", special2: "", special3: "" },
	{ name: "Dimetrodon Gen 2",			rarity: "Common", 	health: null, 	damage: null, 	speed: 112, 	defense: "0%", 	quick: "Defense Shattering Strike", special: "Armor Piercing Rampage", special2: "", special3: "" },
	{ name: "Diplocaulus", 				rarity: "Common", 	health: null, 	damage: null, 	speed: 124, 	defense: "0%", 	quick: "Nullifying Strike", special: "Distracting Impact", special2: "", special3: "" },
	{ name: "Sarcosuchus", 				rarity: "Common", 	health: null, 	damage: null, 	speed: 110, 	defense: "10%",	quick: "Minimal Wounding Strike", special: "Lockdown Strike", special2: "", special3: "" },
];

var Levels = [
	{ name: "Allosaurus",
		levels: [
			{ hp: null, atk: null },
			{ hp: 1396, atk: 512 },
			{ hp: 1466, atk: 538 },
			{ hp: 1539, atk: 564 },
		],
	},
	{ name: "Amargasaurus",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 2036, atk: 400 },
			{ hp: 2137, atk: 420 },
			{ hp: 2244, atk: 441 },
		],
	},
	{ name: "Ankylosaurus",
	},
	{ name: "Ankylosaurus Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1436, atk: 294 },
			{ hp: 1508, atk: 308 },
			{ hp: 1583, atk: 324 },
		],
	},
	{ name: "Apatosaurus",
	},
	{ name: "Dilophosaurus",
	},
	{ name: "Dilophosaurus Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: 838, atk: 379 },
			{ hp: 880, atk: 398 },
		],
	},
	{ name: "Dimetrodon",
		levels: [
			{ hp: null, atk: null },
			{ hp: 1303, atk: 311 },
			{ hp: 1368, atk: 326 },
			{ hp: 1436, atk: 342 },
		],
	},
	{ name: "Edmontosaurus",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1855, atk: 359 },
			{ hp: 1947, atk: 376 },
		],
	},
	{ name: "Einiasuchus",
	},
	{ name: "Einiosaurus",
	},
	{ name: "Euoplocephalus",
		levels: [
			{ hp: 1329, atk: null },
			{ hp: 1396, atk: 295 },
			{ hp: 1466, atk: 310 },
			{ hp: 1539, atk: 325 },
			{ hp: 1616, atk: 341 },
		],
	},
	{ name: "Gorgosaurus",
	},
	{ name: "Iguanodon",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1563, atk: 277 },
			{ hp: 1641, atk: 291 },
			{ hp: 1723, atk: 306 },
		],
	},
	{ name: "Kaprosuchus",
	},
	{ name: "Kentrosaurus",
	},
	{ name: "Lythronax",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1334, atk: 305 },
			{ hp: 1400, atk: 320 },
			{ hp: 1470, atk: 336 },
		],
	},
	{ name: "Majungasaurus",
		levels: [
			{ hp: 1081, atk: 254 },
			{ hp: 1135, atk: 267 },
		],
	},
	{ name: "Megalosaurus",
	},
	{ name: "Monolophosaurus Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: 745, atk: 373 },
			{ hp: 782, atk: 391 },
			{ hp: 821, atk: 411 },
			{ hp: 862, atk: 431 },
			{ hp: 905, atk: 453 },
		],
	},
	{ name: "Nodosaurus",
	},
	{ name: "Nundasuchus",
	},
	{ name: "Ophiacodon",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1368, atk: 326 },
			{ hp: 1436, atk: 342 },
			{ hp: 1508, atk: 359 },
		],
	},
	{ name: "Parasaurolophus",
		levels: [
			{ hp: null, atk: null },
			{ hp: 1582, atk: 276 },
			{ hp: 1661, atk: 290 },
			{ hp: 1744, atk: 305 },
		],
	},
	{ name: "Postosuchus",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1357, atk: 528 },
			{ hp: 1425, atk: 554 },
		],
	},
	{ name: "Proceratosaurus",
	},
	{ name: "Pyroraptor",
	},
	{ name: "Rajasaurus",
	},
	{ name: "Sinoceratops",
	},
	{ name: "Spinosaurus",
	},
	{ name: "Stegosaurus",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1385, atk: 394 },
			{ hp: 1454, atk: 413 },
			{ hp: 1527, atk: 434 },
		],
	},
	{ name: "Suchomimus",
		levels: [
			{ hp: 1072, atk: 207 },
			{ hp: 1126, atk: 218 },
			{ hp: 1182, atk: 228 },
		],
	},
	{ name: "Tanycolagreus",
	},
	{ name: "Tarbosaurus",
		levels: [
			{ hp: 1196, atk: 473 },
			{ hp: 1256, atk: 497 },
		],
	},
	{ name: "Tenontosaurus",
	},
	{ name: "Triceratops",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1583, atk: 468 },
			{ hp: 1662, atk: 491 },
		],
	},
	{ name: "Triceratops Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: 1117, atk: 357 },
			{ hp: 1173, atk: 375 },
		],
	},
	{ name: "Tuojiangosaurus",
	},
	{ name: "Tyrannosaurus Rex",
	},
	{ name: "Tyrannosaurus Gen 2",
	},
	{ name: "Utahraptor",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 950, atk: 509 },
			{ hp: 998, atk: 535 },
		],
	},
	{ name: "Velociraptor",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 635, atk: 430 },
			{ hp: 667, atk: 452 },
		],
	},
	{ name: "Wuerhosaurus",
	},
	{ name: "Dracorex Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1222, atk: 359 },
			{ hp: 1282, atk: 376 },
		],
	},
	{ name: "Purussaurus Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1436, atk: 342 },
			{ hp: 1508, atk: 359 },
			{ hp: 1583, atk: 377 },
		],
	},
	{ name: "Hatzegopteryx",
		levels: [
			{ hp: null, atk: null },
			{ hp: null, atk: null },
			{ hp: 1368, atk: 303 },
			{ hp: 1436, atk: 318 },
			{ hp: 1508, atk: 334 },
		],
	},
	{ name: "Deinocheirus",
		levels: [
			{ hp: 886, atk: 376 },
			{ hp: 931, atk: 394 },
			{ hp: 977, atk: 414 },
			{ hp: 1026, atk: 435 },
		],
	},
	{ name: "Dimetrodon Gen 2",
		levels: [
			{ hp: null, atk: null },
			{ hp: 1303, atk: 311 },
			{ hp: 1368, atk: 326 },
			{ hp: 1436, atk: 342 },
		],
	},
	{ name: "Diplocaulus",
		levels: [
			{ hp: null, atk: null },
			{ hp: 931, atk: 342 },
			{ hp: 977, atk: 359 },
		],
	},
	{ name: "Sarcosuchus",
		levels: [
			{ hp: null, atk: null },
			{ hp: 1303, atk: 311 },
			{ hp: 1368, atk: 326 },
		],
	},
];

var Collection = [
	{ name: "Allosaurus", 				level: 4,	team: false },
	{ name: "Amargasaurus", 			level: 7,	team: false },
	{ name: "Ankylocodon", 				level: 0,	team: false },
	{ name: "Ankylosaurus", 			level: 0,	team: false },
	{ name: "Ankylosaurus Gen 2", 		level: 5,	team: false },
	{ name: "Apatosaurus", 				level: 0,	team: false },
	{ name: "Deinocheirus",				level: 3,	team: false },
	{ name: "Dilophosaurus", 			level: 0,	team: false },
	{ name: "Dilophosaurus Gen 2", 		level: 2,	team: false },
	{ name: "Dimetrodon", 				level: 0,	team: false },
	{ name: "Dimetrodon Gen 2", 		level: 4,	team: false },
	{ name: "Diplocaulus",		 		level: 4,	team: false },
	{ name: "Dracorex Gen 2",			level: 4,	team: false },
	{ name: "Edmontosaurus", 			level: 7,	team: false },
	{ name: "Einiasuchus", 				level: 0,	team: false },
	{ name: "Einiosaurus", 				level: 0,	team: false },
	{ name: "Euoplocephalus", 			level: 4,	team: false },
	{ name: "Gorgosaurus", 				level: 0,	team: false },
	{ name: "Hatzegopteryx",			level: 4,	team: false },
	{ name: "Iguanodon", 				level: 4,	team: false },
	{ name: "Kaprosuchus", 				level: 0,	team: false },
	{ name: "Kentrosaurus", 			level: 0,	team: false },
	{ name: "Lythronax", 				level: 6,	team: false },
	{ name: "Majungasaurus", 			level: 1,	team: false },
	{ name: "Megalosaurus", 			level: 0,	team: false },
	{ name: "Monolophosaurus Gen 2", 	level: 5,	team: false },
	{ name: "Nodosaurus", 				level: 0,	team: false },
	{ name: "Nundasuchus", 				level: 0,	team: false },
	{ name: "Ophiacodon", 				level: 5,	team: false },
	{ name: "Parasaurolophus", 			level: 5,	team: false },
	{ name: "Postosuchus", 				level: 6,	team: false },
	{ name: "Proceratosaurus", 			level: 0,	team: false },
	{ name: "Purussaurus Gen 2",		level: 6,	team: false },
	{ name: "Pyroraptor", 				level: 0,	team: false },
	{ name: "Rajasaurus", 				level: 0,	team: false },
	{ name: "Sarcosuchus",		 		level: 2,	team: false },
	{ name: "Sinoceratops", 			level: 0,	team: false },
	{ name: "Spinosaurus", 				level: 6,	team: false },
	{ name: "Stegosaurus", 				level: 6,	team: false },
	{ name: "Suchomimus", 				level: 3,	team: false },
	{ name: "Tanycolagreus", 			level: 0,	team: false },
	{ name: "Tarbosaurus", 				level: 1,	team: false },
	{ name: "Tenontosaurus", 			level: 0,	team: false },
	{ name: "Triceratops", 				level: 6,	team: false },
	{ name: "Triceratops Gen 2", 		level: 2,	team: false },
	{ name: "Tuojiangosaurus", 			level: 6,	team: false },
	{ name: "Tyrannosaurus Rex", 		level: 0,	team: false },
	{ name: "Tyrannosaurus Rex Gen 2", 	level: 0,	team: false },
	{ name: "Utahraptor", 				level: 7,	team: false },
	{ name: "Velociraptor", 			level: 4,	team: false },
	{ name: "Wuerhosaurus", 			level: 6,	team: false },
];


var Images = [
	{ name: "Allosaurus", 				img: "https://metahub.info/wp-content/uploads/2018/05/Allosaurus.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Allosauru.png" },
	{ name: "Amargasaurus", 			img: "https://metahub.info/wp-content/uploads/2018/05/Amargasaurus.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Amargasau.png" },
	{ name: "Ankylosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Ankylosau.png" },
	{ name: "Ankylosaurus Gen 2", 		img: "https://metahub.info/wp-content/uploads/2018/05/Ankylosaurus-Gen-2.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Ankylosau2.png" },
	{ name: "Apatosaurus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Apatosaur.png" },
	{ name: "Dilophosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Dilophosa.png" },
	{ name: "Dilophosaurus Gen 2", 		img: "https://metahub.info/wp-content/uploads/2018/05/Dilophosaurus-Gen-2.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Dilophosa2.png" },
	{ name: "Dimetrodon", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Dimetrodo.png" },
	{ name: "Edmontosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Edmontosa.png" },
	{ name: "Einiasuchus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Einiasuch.png" },
	{ name: "Einiosaurus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Einiosaur.png" },
	{ name: "Euoplocephalus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Euoplocep.png" },
	{ name: "Gorgosaurus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Gorgosaur.png" },
	{ name: "Iguanodon", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Iguanodon.png" },
	{ name: "Kaprosuchus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Kaprosuch.png" },
	{ name: "Kentrosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Kentrosau.png" },
	{ name: "Lythronax", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Lythronax.png" },
	{ name: "Majungasaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Majungasa.png" },
	{ name: "Megalosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Megalosau.png" },
	{ name: "Monolophosaurus Gen 2", 	img: "https://metahub.info/wp-content/uploads/2018/05/Monolophosaurus-Gen-2.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Monolopho2.png" },
	{ name: "Nodosaurus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Nodosauru.png" },
	{ name: "Nundasuchus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Nundasuch.png" },
	{ name: "Ophiacodon", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Ophiacodo.png" },
	{ name: "Parasaurolophus", 			img: "https://metahub.info/wp-content/uploads/2018/05/Parasaurolophus.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Parasauro.png" },
	{ name: "Postosuchus", 				img: "https://metahub.info/wp-content/uploads/2018/05/Postosuchus.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Postosuch.png" },
	{ name: "Proceratosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Procerato.png" },
	{ name: "Pyroraptor", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Pyrorapto.png" },
	{ name: "Rajasaurus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Rajasauru.png" },
	{ name: "Sinoceratops", 			img: "" },
	{ name: "Spinosaurus", 				img: "" },
	{ name: "Stegosaurus", 				img: "https://metahub.info/wp-content/uploads/2018/05/Stegosaurus.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Stegosaur.png" },
	{ name: "Suchomimus", 				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Suchominu.png" },
	{ name: "Tanycolagreus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tanycolag.png" },
	{ name: "Tarbosaurus", 				img: "https://metahub.info/wp-content/uploads/2018/05/Tarbosaurus.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tarbosaur.png" },
	{ name: "Tenontosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tenontosa.png" },
	{ name: "Triceratops", 				img: "https://metahub.info/wp-content/uploads/2018/05/Triceratops.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tricerato.png" },
	{ name: "Triceratops Gen 2", 		img: "https://metahub.info/wp-content/uploads/2018/05/Triceratops-Gen-2.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tricerato2.png" },
	{ name: "Tuojiangosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tuojiango.png" },
	{ name: "Tyrannosaurus Rex", 		img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tyrannosa.png" },
	{ name: "Tyrannosaurus Gen 2", 		img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Tyrannosa2.png" },
	{ name: "Utahraptor", 				img: "https://metahub.info/wp-content/uploads/2018/05/Utahraptor.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Utahrapto.png" },
	{ name: "Velociraptor", 			img: "https://metahub.info/wp-content/uploads/2018/05/Velociraptor.png" },//"https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Velocirap.png" },
	{ name: "Wuerhosaurus", 			img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Wuerhosau.png" },
	{ name: "Dracorex Gen 2",			img: "https://metahub.info/wp-content/uploads/2018/06/Dracorex2.png" },
	{ name: "Purussaurus Gen 2",		img: "https://metahub.info/wp-content/uploads/2018/06/JWA_Profile_Purussaurus_GEN2_result.jpg" },
	{ name: "Hatzegopteryx",			img: "https://metahub.info/wp-content/uploads/2018/09/Hatzegop.png" },
	{ name: "Deinocheirus",				img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Deinocheirus.png" },
	{ name: "Dimetrodon Gen 2", 		img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Dimetrodo2.png" },
	{ name: "Diplocaulus",		 		img: "https://github.com/apavlinovic/jurassic-world-alive-assets/raw/master/Sprite/Img_Diplocaulus.png" },
	{ name: "Sarcosuchus",		 		img: "https://metahub.info/wp-content/uploads/2018/06/JWA_Profile_Sarcosuchus_result.jpg" },
];
// https://github.com/Incien104/Julive/tree/master/assets/dinoCards
// https://github.com/Incien104/Julive/tree/master/1.2.22/JW%20Alive_com.ludia.jw2/assets/Database/Assets/Data/CreaturesAttributesData
// https://drive.google.com/drive/folders/1Uwav8lnULEih-jCIK8EaE5Nueui8Lq35

// src: "Img_Allopachy.png" },
// src: "Img_Amargado.png" },
// src: "Img_Amargoce.png" },
// src: "Img_Ankyntros.png" },
// src: "Img_Argentino.png" },
// src: "Img_Corner.png" },
// src: "Img_Diplocaulus2.png" },
// src: "Img_Erlidominus.png" },
// src: "Img_Erlikosaurus.png" },
// src: "Img_Erlikosaurus2.png" },
// src: "Img_Gorgosuch.png" },
// src: "Img_Indominus.png" },
// src: "Img_Koolasuchus.png" },
// src: "Img_Koolasuchus2.png" },
// src: "Img_Majundasuch.png" },
// src: "Img_Megalosuc.png" },
// src: "Img_Monolopho.png" },
// src: "Img_Monostego.png" },
// src: "Img_Nodopatos.png" },
// src: "Img_Pachyrhin.png" },
// src: "Img_Paramargo.png" },
// src: "Img_Postimetro.png" },
// src: "Img_Rajakylo.png" },
// src: "Img_Secodonto.png" },
// src: "Img_Spinosaur.png" },
// src: "Img_Spinotah.png" },
// src: "Img_Stegocera.png" },
// src: "Img_Trykosaur.png" },
// src: "Img_Utahrhino.png" },
// src: "Img_ouranosau.png" },

var Tiers = [
	{ name: "Alankylosaurus",			tier: "Apex" },
	{ name: "Alanqa",					tier: "Survivor" },
	{ name: "Allosaurus",				tier: "Hatchling" },
	{ name: "Allosinosaurus",			tier: "Apex" },
	{ name: "Amargasaurus",				tier: "Hatchling" },
	{ name: "Amargocephalus",			tier: "Specialist" },
	{ name: "Ankylocodon",				tier: "Specialist" },
	{ name: "Ankylosaurus",				tier: "Specialist" },
	{ name: "Ankylosaurus Gen 2",		tier: "Specialist" },
	{ name: "Ankyntrosaurus",			tier: "Alpha" },
	{ name: "Apatosaurus",				tier: "Hatchling" },
	{ name: "Arambourgiania",			tier: "Survivor" },
	{ name: "Argentinosaurus",			tier: "Survivor" },
	{ name: "Baryonyx",					tier: "Survivor" },
	{ name: "Baryonyx Gen 2",			tier: "Hatchling" },
	{ name: "Blue",						tier: "Alpha" },
	{ name: "Brachiosaurus",			tier: "Alpha" },
	{ name: "Carnotaurus",				tier: "Hatchling" },
	{ name: "Charlie",					tier: "Survivor" },
	{ name: "Concavenator",				tier: "Specialist" },
	{ name: "Deinocheirus",				tier: "Hatchling" },
	{ name: "Delta",					tier: "Survivor" },
	{ name: "Dilophosaurus",			tier: "Specialist" },
	{ name: "Dilophosaurus Gen 2",		tier: "Hatchling" },
	{ name: "Diloracheirus",			tier: "Apex" },
	{ name: "Diloranosaurus",			tier: "Alpha" },
	{ name: "Dimetrodon",				tier: "Survivor" },
	{ name: "Dimetrodon Gen 2",			tier: "Specialist" },
	{ name: "Diorajasaur",				tier: "Alpha" },
	{ name: "Diplocaulus",				tier: "Hatchling" },
	{ name: "Diplocaulus Gen 2",		tier: "Specialist" },
	{ name: "Diplotator",				tier: "Survivor" },
	{ name: "Dracorex",					tier: "Hatchling" },
	{ name: "Dracorex Gen 2",			tier: "Carcass" },
	{ name: "Dsungaripterus",			tier: "Specialist" },
	{ name: "Echo",						tier: "Specialist" },
	{ name: "Edmontosaurus",			tier: "Specialist" },
	{ name: "Einiasuchus",				tier: "Survivor" },
	{ name: "Einiosaurus",				tier: "Hatchling" },
	{ name: "Erlidominus",				tier: "Apex" },
	{ name: "Erlikosaurus",				tier: "Alpha" },
	{ name: "Erlikosaurus Gen 2",		tier: "Survivor" },
	{ name: "Euoplocephalus",			tier: "Hatchling" },
	{ name: "Gallimimus",				tier: "Specialist" },
	{ name: "Gigaspikasaur",			tier: "Survivor" },
	{ name: "Giraffatitan",				tier: "Survivor" },
	{ name: "Gorgosaurus",				tier: "Specialist" },
	{ name: "Gorgosuchus",				tier: "Survivor" },
	{ name: "Gryposuchus",				tier: "Specialist" },
	{ name: "Hatzegopteryx",			tier: "Hatchling" },
	{ name: "Iguanodon",				tier: "Hatchling" },
	{ name: "Indominus Rex",			tier: "Apex" },
	{ name: "Indoraptor",				tier: "Apex" },
	{ name: "Irritator",				tier: "Specialist" },
	{ name: "Irritator Gen 2",			tier: "Carcass" },
	{ name: "Kaprosuchus",				tier: "Survivor" },
	{ name: "Kentrosaurus",				tier: "Survivor" },
	{ name: "Koolasuchus",				tier: "Survivor" },
	{ name: "Koolasuchus Gen 2",		tier: "Specialist" },
	{ name: "Lythronax",				tier: "Hatchling" },
	{ name: "Magnapyritor",				tier: "Apex" },
	{ name: "Majundasuchus",			tier: "Survivor" },
	{ name: "Majungasaurus",			tier: "Hatchling" },
	{ name: "Megalosaurus",				tier: "Hatchling" },
	{ name: "Megalosuchus",				tier: "Alpha" },
	{ name: "Monolometrodon",			tier: "Specialist" },
	{ name: "Monolophosaurus",			tier: "Specialist" },
	{ name: "Monolophosaurus Gen 2",	tier: "Hatchling" },
	{ name: "Monomimus",				tier: "Apex" },
	{ name: "Monostegotops",			tier: "Alpha" },
	{ name: "Nodopatosaurus",			tier: "Survivor" },
	{ name: "Nodopatotitan",			tier: "Survivor" },
	{ name: "Nodosaurus",				tier: "Specialist" },
	{ name: "Nundasuchus",				tier: "Specialist" },
	{ name: "Ophiacodon",				tier: "Hatchling" },
	{ name: "Ornithomimus",				tier: "Survivor" },
	{ name: "Ouranosaurus",				tier: "Alpha" },
	{ name: "Paramoloch",				tier: "Alpha" },
	{ name: "Parasaurolophus",			tier: "Hatchling" },
	{ name: "Postimetrodon",			tier: "Alpha" },
	{ name: "Postosuchus",				tier: "Survivor" },
	{ name: "Proceratosaurus",			tier: "Specialist" },
	{ name: "Pteranodon",				tier: "Survivor" },
	{ name: "Purrusaurus",				tier: "Specialist" },
	{ name: "Purrusaurus Gen 2",		tier: "Hatchling" },
	{ name: "Pyroraptor",				tier: "Survivor" },
	{ name: "Pyrritator",				tier: "Apex" },
	{ name: "Quetzalcoatlus",			tier: "Hatchling" },
	{ name: "Rajakylosaurus",			tier: "Apex" },
	{ name: "Rajasaurus",				tier: "Alpha" },
	{ name: "Sarcorixis",				tier: "Survivor" },
	{ name: "Sarcosuchus",				tier: "Hatchling" },
	{ name: "Secodontosaurus",			tier: "Specialist" },
	{ name: "Sinoceratops",				tier: "Survivor" },
	{ name: "Spinosaurus",				tier: "Survivor" },
	{ name: "Spinosaurus Gen 2",		tier: "Survivor" },
	{ name: "Spinotahraptor",			tier: "Alpha" },
	{ name: "Spinotasuchus",			tier: "Apex" },
	{ name: "Stegoceratops",			tier: "Alpha" },
	{ name: "Stegodeus",				tier: "Apex" },
	{ name: "Stegosaurus",				tier: "Hatchling" },
	{ name: "Stygimoloch",				tier: "Survivor" },
	{ name: "Stygimoloch Gen 2",		tier: "Carcass" },
	{ name: "Suchomimus",				tier: "Specialist" },
	{ name: "Suchotator",				tier: "Alpha" },
	{ name: "Tanycolagreus",			tier: "Alpha" },
	{ name: "Tarbosaurus",				tier: "Hatchling" },
	{ name: "Tenontosaurus",			tier: "Specialist" },
	{ name: "Tragodistis",				tier: "Apex" },
	{ name: "Triceratops",				tier: "Specialist" },
	{ name: "Triceratops Gen 2",		tier: "Hatchling" },
	{ name: "Trykosaurus",				tier: "Apex" },
	{ name: "Tryostronix",				tier: "Apex" },
	{ name: "Tuojiangosaurus",			tier: "Specialist" },
	{ name: "Tuoramoloch",				tier: "Alpha" },
	{ name: "Tupandactylus",			tier: "Specialist" },
	{ name: "Tyrannosaurus Rex",		tier: "Alpha" },
	{ name: "Tyrannosaurus Rex Gen 2",	tier: "Hatchling" },
	{ name: "Utahraptor",				tier: "Survivor" },
	{ name: "Utarinex",					tier: "Apex" },
	{ name: "Utasinoraptor",			tier: "Alpha" },
	{ name: "Velociraptor",				tier: "Specialist" },
	{ name: "Wuerhosaurus",				tier: "Specialist" },
];

// depletes some DNA from sources and adds to result, but might not create result
var Fusions = [
	{ result: "Ankylocodon", source1: "Ophiacodon", level1: 5, source2: "Ankylosaurus Gen 2", level2: 5 },
];
